# Generated by Django 5.1.6 on 2025-02-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_to', to='core.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_from', to='core.card'),
        ),
    ]
