# Generated by Django 5.1.6 on 2025-02-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_receiver_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Uzbek Som'), ('RUB', 'Russian Rubles'), ('USD', 'US Dollar'), ('KRW', 'Korean Won'), ('EUR', 'Euro')], default='USD', max_length=3),
        ),
    ]
