# Generated by Django 5.1.6 on 2025-02-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_card_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='received_currency',
            field=models.CharField(choices=[('UZS', 'Uzbek Som'), ('RUB', 'Russian Rubles'), ('USD', 'US Dollar'), ('KRW', 'Korean Won'), ('EUR', 'Euro')], max_length=3, null=True),
        ),
    ]
