# Generated by Django 5.1.6 on 2025-02-26 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_complaint_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
    ]
