# Generated by Django 5.2.6 on 2026-02-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="core.user",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="core.user",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacted_by",
                to="core.user",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="core.user",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_transactions",
                to="core.user",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_transactions",
                to="core.user",
            ),
        ),
    ]
